<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OpenBuzz.VirtualControllers</RootNamespace>
    <AssemblyName>obz-controllers</AssemblyName>
    <ApplicationDefaultFont>Segoe UI, 9pt</ApplicationDefaultFont>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenBuzz.Input\OpenBuzz.Input.csproj" />
  </ItemGroup>

</Project>
