<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenBuzz.Audio\OpenBuzz.Audio.csproj" />
    <ProjectReference Include="..\..\src\OpenBuzz.Quiz\OpenBuzz.Quiz.csproj" />
    <ProjectReference Include="..\..\src\OpenBuzz.Graphics\OpenBuzz.Graphics.csproj" />
    <ProjectReference Include="..\..\src\OpenBuzz.Animation\OpenBuzz.Animation.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OpenBuzz.Cli</RootNamespace>
    <AssemblyName>obz</AssemblyName>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

</Project>
