<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OpenBuzz.Ui</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenBuzz.Input\OpenBuzz.Input.csproj" />
    <ProjectReference Include="..\OpenBuzz.Graphics\OpenBuzz.Graphics.csproj" />
    <ProjectReference Include="..\OpenBuzz.Animation\OpenBuzz.Animation.csproj" />
  </ItemGroup>

</Project>
